#%RAML 1.0 NamedExample

{
  "orderId": "123456",
  "items":[
    {
      "itemName":"abc",
      "price":1000,
      "quantity":1
    },
    {
      "itemName":"xyz",
      "price":1922,
      "quantity":3
    }
  ]
}
