{
  "bucketName": "g13accounts",
  "sseAlgorithm": null,
  "ongoingRestore": false,
  "storageClass": null,
  "sseCustomerAlgorithm": null,
  "contentDisposition": null,
  "contentEncoding": null,
  "contentType": "text/plain",
  "key": "Accounts/Account2.txt",
  "sseCustomerKeyMd5": null,
  "contentMD5": null,
  "requesterCharged": false,
  "replicationStatus": null,
  "cacheControl": null,
  "httpExpiresDate": null,
  "versionId": "feN0qiwMi.QByyshdxZ_A_DuE0fQgJyw",
  "sseAwsKmsKeyId": null,
  "restoreExpirationTime": null,
  "expirationTimeRuleId": null,
  "expirationTime": null,
  "contentLanguage": null,
  "contentLength": 248,
  "etag": "190286528f36fea457c5b983c90dd026",
  "lastModified": |2021-11-01T12:48:03|,
  "userMetadata": {},
  "redirectLocation": null
}